name: Daily Python Script

on:
  schedule:
    - cron: '30 3 * * *'  # 3:30 AM UTC = 9:00 AM IST
  workflow_dispatch:  # Optional: allows manual run

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    env:  # ✅ Add this section to expose secrets to your script
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.11.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.11'

      - name: Install dependencies (if needed)
        run: |
          pip install -r requirements.txt || echo "No requirements file"

      - name: Run script
        run: python MorningReport.py
